// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzsDqOf6evEfGLPtu1DZDgd81vHYroQYc',
    appId: '1:531763765810:web:80bb663abf167fe35a922b',
    messagingSenderId: '531763765810',
    projectId: 'giantodental',
    authDomain: 'giantodental.firebaseapp.com',
    storageBucket: 'giantodental.firebasestorage.app',
    measurementId: 'G-WP0LBYNL5Y',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMwUdNt4Vs4nbGykFdF2NUd2YO2QwcZTM',
    appId: '1:531763765810:ios:2fb56514d32e731e5a922b',
    messagingSenderId: '531763765810',
    projectId: 'giantodental',
    storageBucket: 'giantodental.firebasestorage.app',
    iosBundleId: 'com.example.teamProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMwUdNt4Vs4nbGykFdF2NUd2YO2QwcZTM',
    appId: '1:531763765810:ios:2fb56514d32e731e5a922b',
    messagingSenderId: '531763765810',
    projectId: 'giantodental',
    storageBucket: 'giantodental.firebasestorage.app',
    iosBundleId: 'com.example.teamProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzsDqOf6evEfGLPtu1DZDgd81vHYroQYc',
    appId: '1:531763765810:web:de2faf25239d0c2b5a922b',
    messagingSenderId: '531763765810',
    projectId: 'giantodental',
    authDomain: 'giantodental.firebaseapp.com',
    storageBucket: 'giantodental.firebasestorage.app',
    measurementId: 'G-3W12BX5VXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJZ_SiUeJsI6OtGFNXN4GLfQZOiS0eQJM',
    appId: '1:531763765810:android:432fd69be86c9a975a922b',
    messagingSenderId: '531763765810',
    projectId: 'giantodental',
    storageBucket: 'giantodental.firebasestorage.app',
  );

}