import 'package:flutter/material.dart';
import 'informasi_akun_simpan.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [InformasiAkunEdit()])),
    );
  }
}

class InformasiAkunEdit extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 30,
                top: 83,
                child: Opacity(
                  opacity: 0.65,
                  child: Container(
                    width: 33,
                    height: 33,
                    decoration: ShapeDecoration(
                      color: const Color(0xFFE7E7E7),
                      shape: OvalBorder(),
                    ),
                    child: IconButton(
                      icon: Image.asset(
                        'assets/icons/arrow-back.png',
                        width: 19.8,
                        height: 19.8,
                      ),
                      onPressed: () {
                        Navigator.pop(context);
                      },
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 100,
                top: 88,
                child: Text(
                  'Informasi Akun',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 20,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w600,
                    height: 1.05,
                  ),
                ),
              ),
              Positioned(
                left: 33,
                top: 193,
                child: Container(
                  width: 328,
                  height: 38,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFFD9D9D9),
                      ),
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 172,
                child: Text(
                  'Nama Pengguna',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                    height: 1.75,
                    decoration: TextDecoration.none,
                      decorationColor: Colors.transparent,
                  ),
                ),
              ),
              Positioned(
                left: 54,
                top: 201,
                child: Text(
                  'Devagitisar1',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.75,
                    decoration: TextDecoration.none,
                      decorationColor: Colors.transparent,
                  ),
                ),
              ),
              Positioned(
                left: 33,
                top: 264,
                child: Container(
                  width: 328,
                  height: 38,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFFD9D9D9),
                      ),
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 243,
                child: Text(
                  'Nama',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                    height: 1.75,
                    decoration: TextDecoration.none,
                      decorationColor: Colors.transparent,
                  ),
                ),
              ),
              Positioned(
                left: 54,
                top: 272,
                child: Text(
                  'Deva Gitisarii',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.75,
                    decoration: TextDecoration.none,
                      decorationColor: Colors.transparent,
                  ),
                ),
              ),
              Positioned(
                left: 33,
                top: 335,
                child: Container(
                  width: 328,
                  height: 38,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFFD9D9D9),
                      ),
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 314,
                child: Text(
                  'No Telepon',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                    height: 1.75,
                    decoration: TextDecoration.none,
                      decorationColor: Colors.transparent,
                  ),
                ),
              ),
              Positioned(
                left: 54,
                top: 343,
                child: Text(
                  '0877889284',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.75,
                    decoration: TextDecoration.none,
                      decorationColor: Colors.transparent,
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 406,
                child: Container(
                  width: 328,
                  height: 38,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFFD9D9D9),
                      ),
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 41,
                top: 385,
                child: Text(
                  'Email',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                    height: 1.75,
                    decoration: TextDecoration.none,
                      decorationColor: Colors.transparent,
                  ),
                ),
              ),
              Positioned(
                left: 58,
                top: 414,
                child: Text(
                  'devagitisar49@gmail.com',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w400,
                    height: 1.75,
                    decoration: TextDecoration.none,
                      decorationColor: Colors.transparent,
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 477,
                child: Container(
                  width: 328,
                  height: 63,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFFD9D9D9),
                      ),
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 41,
                top: 456,
                child: Text(
                  'Alamat ',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                    height: 1.75,
                    decoration: TextDecoration.none,
                      decorationColor: Colors.transparent,
                  ),
                ),
              ),
              Positioned(
                left: 58,
                top: 485,
                child: SizedBox(
                  width: 297,
                  height: 42,
                  child: Text(
                    'Jl. Haji Maksum (Sebelah TPA Al Kautsar)\nSAWANGAN, KOTA DEPOK, JAWA BARAT, ID 116511\n',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                      height: 1.75,
                      decoration: TextDecoration.none,
                      decorationColor: Colors.transparent,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 284,
                top: 566,
                child: GestureDetector(
                  onTap: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (context) => InformasiAkunSimpan(),
                      ),
                    );
                  },
                  child: Container(
                    width: 81,
                    height: 35,
                    decoration: ShapeDecoration(
                      color: const Color(0xFF0C3345),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(10),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 312,
                top: 573,
                child: GestureDetector(
                  onTap: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (context) => InformasiAkunSimpan(),
                      ),
                    );
                  },
                  child: Text(
                    'Edit',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 13,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                      height: 1.62,
                      decoration: TextDecoration.none,
                      decorationColor: Colors.transparent,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}

