import 'package:flutter/material.dart';
import 'informasi_akun_edit.dart';
import 'ubah-kata-sandi.dart';



void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Pengaturan(),
        ]),
      ),
    );
  }
}

class Pengaturan extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 30,
                top: 83,
                child: Opacity(
                  opacity: 0.65,
                  child: Container(
                    width: 33,
                    height: 33,
                    decoration: ShapeDecoration(
                      color: const Color(0xFFE7E7E7),
                      shape: OvalBorder(),
                    ),
                    child: IconButton(
                        icon: Image.asset(
                          'assets/icons/arrow-back.png',
                          width: 24,
                          height: 24,
                        ),
                        onPressed: () => Navigator.pop(context),
                      ),
                  ),
                ),
              ),
              Positioned(
                left: 315,
                top: 751,
                child: Container(
                  width: 40,
                  height: 40,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 36.60,
                top: 89.60,
                child: Container(
                  width: 19.80,
                  height: 19.80,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 126,
                top: 218,
                child: Text(
                  'Nama  Pengguna',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 16,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w600,
                    height: 1.20,
                  ),
                ),
              ),
              Positioned(
                left: 139,
                top: 88,
                child: Text(
                  'Pengaturan',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 20,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w600,
                    height: 1.05,
                  ),
                ),
              ),
              Positioned(
                left: 42,
                top: 161,
                child: GestureDetector(
                  onTap: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (context) => InformasiAkunEdit(),
                      ),
                    );
                  },
                  child: Container(
                    width: 315,
                    height: 51,
                    decoration: ShapeDecoration(
                      color: Color(0xFF0C3345),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(10),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 42,
                top: 236,
                child: GestureDetector(
                  onTap: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (context) => UbahKataSandi(),
                      ),
                    );
                  },
                  child: Container(
                    width: 315,
                    height: 51,
                    decoration: ShapeDecoration(
                      color: Color(0xFF0C3345),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(10),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 42,
                top: 314,
                child: Container(
                  width: 315,
                  height: 51,
                  decoration: ShapeDecoration(
                    color: Color(0xFF0FF0101),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 67,
                top: 178,
                child: Text(
                  'Informasi Akun',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w600,
                    height: 1.20,
                    decoration: TextDecoration.none,
                      decorationColor: Colors.transparent,
                  ),
                ),
              ),
              Positioned(
                left: 65,
                top: 253,
                child: Text(
                  'Ubah Kata Sandi',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w600,
                    height: 1.20,
                  ),
                ),
              ),
              Positioned(
                left: 61,
                top: 329,
                child: Text(
                  'Nonaktifkan Akun',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w600,
                    height: 1.20,
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}


