import 'package:flutter/material.dart';


void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          UbahKataSandi(),
        ]),
      ),
    );
  }
}

class UbahKataSandi extends StatelessWidget {
  const UbahKataSandi({super.key});

  InputDecoration customInputDecoration(String hint) {
  return InputDecoration(
    hintText: hint,
    filled: true,
    fillColor: Color(0xFFF3F3F3),
    contentPadding: EdgeInsets.symmetric(vertical: 14, horizontal: 18),
    hintStyle: TextStyle(color: Colors.grey, fontSize: 14),
    enabledBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(12),
      borderSide: BorderSide.none,
    ),
    focusedBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(12),
      borderSide: BorderSide(color: Color(0xFF43A047), width: 1.2),
    ),
  );
}

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: Center(
  child: ConstrainedBox(
    constraints: BoxConstraints(
      maxWidth: 360, // Ukuran sesuai tampilan Figma (tidak melebar)
    ),
    child: ListView(
      padding: EdgeInsets.all(20),
      children: [
        Row(
          children: [
            IconButton(
              icon: Icon(Icons.arrow_back, color: Colors.black),
              onPressed: () => Navigator.pop(context),
            ),
            SizedBox(width: 5),
            Text(
              'Ubah Kata Sandi',
              style: TextStyle(
                fontSize: 20,
                fontWeight: FontWeight.w600,
                color: Colors.black,
              ),
            )
          ],
        ),

        SizedBox(height: 25),

        // LABEL + TEXTFIELD 1
        Text("Kata sandi saat ini*",
            style: TextStyle(fontSize: 14, fontWeight: FontWeight.w500)),
        SizedBox(height: 8),
        TextField(
          decoration: customInputDecoration("Masukkan sandi saat ini"),
          obscureText: true,
        ),

        SizedBox(height: 20),

        // LABEL + TEXTFIELD 2
        Text("Kata sandi baru*",
            style: TextStyle(fontSize: 14, fontWeight: FontWeight.w500)),
        SizedBox(height: 8),
        TextField(
          decoration: customInputDecoration("Minimal 8 karakter"),
          obscureText: true,
        ),

        SizedBox(height: 20),

        // LABEL + TEXTFIELD 3
        Text("Konfirmasi kata sandi",
            style: TextStyle(fontSize: 14, fontWeight: FontWeight.w500)),
        SizedBox(height: 8),
        TextField(
          decoration: customInputDecoration("Minimal 8 karakter"),
          obscureText: true,
        ),

        SizedBox(height: 30),

        Align(
          alignment: Alignment.centerRight,
          child: ElevatedButton(
            onPressed: () {},
            style: ElevatedButton.styleFrom(
              backgroundColor: Color(0xFF43A047),
              padding: EdgeInsets.symmetric(vertical: 12, horizontal: 28),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(10),
              ),
            ),
            child: Text(
              "Simpan",
              style: TextStyle(
                color: Colors.white,
                fontSize: 14,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
        ),
      ],
    ),
  ),
),
    );
  }
}